import org.jetbrains.kotlin.gradle.tasks.KotlinCompile

/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    java
    idea
    `maven-publish`
    kotlin("jvm") version "1.6.10"
}

repositories {
    mavenLocal()
    maven {
        url = uri("https://repo.dmulloy2.net/repository/public/")
    }

    maven {
        url = uri("https://jitpack.io/")
    }

    maven {
        url = uri("https://repo.codemc.io/repository/nms/")
    }

    maven {
        url = uri("https://repo.maven.apache.org/maven2/")
    }
    mavenCentral()
}

val library: Configuration by configurations.creating
dependencies {
    fun implementationAndLibrary(dependencyNotation: String) {
        implementation(dependencyNotation)
        library(dependencyNotation)
    }

//    implementation("com.comphenix.protocol:ProtocolLib:4.7.0")
    compileOnly("com.destroystokyo.paper:paper:1.12.2-R0.1-SNAPSHOT")
    implementationAndLibrary("org.projectlombok:lombok:1.18.22")

    implementationAndLibrary("org.jetbrains.kotlin:kotlin-stdlib")
    implementationAndLibrary("org.jetbrains.kotlin:kotlin-stdlib-jdk8:1.6.10")
}

group = "AryAntiCheat"
version = "1.0"
description = "AryAnticheat"
java.sourceCompatibility = JavaVersion.VERSION_1_8

publishing {
    publications.create<MavenPublication>("maven") {
        from(components["java"])
    }
}

tasks.withType<JavaCompile> {
    options.encoding = "UTF-8"
}

val compileKotlin: KotlinCompile by tasks
compileKotlin.kotlinOptions {
    jvmTarget = "1.8"
}

val compileTestKotlin: KotlinCompile by tasks
compileTestKotlin.kotlinOptions {
    jvmTarget = "1.8"
}

tasks {
    jar {
        from(
            library.map {
                if (it.isDirectory) it
                else zipTree(it)
            }
        )
        duplicatesStrategy = DuplicatesStrategy.INCLUDE
    }
}